name: Daily XP Sync

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  sync-xp:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repo
        uses: actions/checkout@v3

      - name: 🧰 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📁 Change to correct directory
        run: cd magnusiba-xp-sync

      - name: 📦 Install dependencies
        run: npm install
        working-directory: magnusiba-xp-sync

      - name: 🚀 Run XP Sync Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: node syncXP.js
        working-directory: magnusiba-xp-sync
